/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘CreateFlight&Update...st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir55 = null;
        public BindDirection bind_dir56 = null;
        public BindDirection bind_dir57 = null;
        public BindDirection bind_dir58 = null;
        public HP.ST.Ext.BasicActivities.DataCursorActivity DataCursorActivity24 = null;
        public BindDirection bind_dir59 = null;
        public HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy DataCursorActivity24_Policy = null;
        public BindDirection bind_dir60 = null;
        public BindDirection bind_dir61 = null;
        public BindDirection bind_dir62 = null;
        public BindDirection bind_dir63 = null;
        public BindDirection bind_dir64 = null;
        public BindDirection bind_dir65 = null;
        public BindDirection bind_dir66 = null;
        public BindDirection bind_dir67 = null;
        public BindDirection bind_dir68 = null;
        public BindDirection bind_dir69 = null;
        public BindDirection bind_dir70 = null;
        public BindDirection bind_dir71 = null;
        public BindDirection bind_dir72 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        FeaturesGroup fg1 = new FeaturesGroup();
            fg1.Add(new LicenseFeature("UnifiedFunctionalTesting","1.0"));
            fg1.Add(new LicenseFeature("UnifiedFunctionalTesting","1.1"));
            fg1.Add(new LicenseFeature("UnifiedFunctionalTesting","1.2"));
            features.Add(fg1);
            FeaturesGroup fg2 = new FeaturesGroup();
            return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.DataFetchActivity20 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity20");
            _flow.DataFetchActivity17 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity17");
            _flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.DataExporterActivity19 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity19");
            _flow.DataExporterActivity22 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity22");
            _flow.DataExporterCloseActivity23 = new HP.ST.Ext.BasicActivities.DataExporterCloseActivity(_context,"DataExporterCloseActivity23");
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.DataDisconnectActivity18 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity18");
            _flow.DataDisconnectActivity21 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity21");
            this.DataCursorActivity24 = new HP.ST.Ext.BasicActivities.DataCursorActivity(_context,"DataCursorActivity24");
            this.DataCursorActivity24_Policy = new HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy();
            _flow.Sequence16 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence16");
            _flow.StServiceCallActivity9 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity9");
            _flow.StServiceCallActivity11 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity11");
            _flow.CallQTPTest12 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest12");
            _flow.StServiceCallActivity14 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity14");
            _flow.CallQTPTest15 = new HP.ST.Ext.UFTActivity.QtpTestActivity(_context,"CallQTPTest15");
            _flow.DataFetchActivity20.Comment = @"";
            _flow.DataFetchActivity20.IconPath = @"";
            _flow.DataFetchActivity20.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity20.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity20_QueryParameters_Document = new XmlDocument();
            DataFetchActivity20_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity20Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>1111aa30-5e61-445a-8ed9-7b94bf89de7f</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>FlidhtInfo!Output</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>FlidhtInfo</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{FlidhtInfo!Output.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Output$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity20_QueryParameters_Document.LoadXml(xmlDataFetchActivity20Params);
            _flow.DataFetchActivity20.QueryParameters = DataFetchActivity20_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("FlidhtInfo!Output", _flow.DataFetchActivity20);
            this.Activities.Add (_flow.DataFetchActivity20);
            _flow.DataFetchActivity17.Comment = @"";
            _flow.DataFetchActivity17.IconPath = @"";
            _flow.DataFetchActivity17.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity17.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity17_QueryParameters_Document = new XmlDocument();
            DataFetchActivity17_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity17Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>32df716a-737c-40c1-a74a-53537eb3c9ac</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>FlidhtInfo!Input</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>FlidhtInfo</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{FlidhtInfo!Input.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Input$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity17_QueryParameters_Document.LoadXml(xmlDataFetchActivity17Params);
            _flow.DataFetchActivity17.QueryParameters = DataFetchActivity17_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("FlidhtInfo!Input", _flow.DataFetchActivity17);
            this.Activities.Add (_flow.DataFetchActivity17);
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.JMSClientID = @"";
            _flow.StartActivity1.JMS.SSLPassword = @"";
            _flow.StartActivity1.JMS.SSLTrustedCertificate = @"";
            _flow.StartActivity1.JMS.SSLIdentity = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 1 iteration";
            _flow.Loop2.NumberOfIterations = (int)1;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (this.DataCursorActivity24);
            _flow.Loop2.Activities.Add (_flow.Sequence16);
            this.Activities.Add (_flow.Loop2);
            _flow.DataExporterActivity19.Comment = @"";
            _flow.DataExporterActivity19.IconPath = @"";
            VTDPropertyInfoBase pi109 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter55 = new VTDObjectGetter(pi109);
            VTDPropertyInfoBase pi110 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter55 = new VTDObjectSetter(pi110);
            binding_setter55 = new StringFormaterDecorator(binding_setter55,"{Step.DataFetchActivity17.OutTable}");
            bind_dir55 = new BindDirection(_flow.DataFetchActivity17,binding_getter55,binding_setter55,BindTargetType.ToInProperty);
            _flow.DataExporterActivity19.InDirections.Add(bind_dir55);
            this.Activities.Add (_flow.DataExporterActivity19);
            _flow.DataExporterActivity22.Comment = @"";
            _flow.DataExporterActivity22.IconPath = @"";
            VTDPropertyInfoBase pi111 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter56 = new VTDObjectGetter(pi111);
            VTDPropertyInfoBase pi112 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter56 = new VTDObjectSetter(pi112);
            binding_setter56 = new StringFormaterDecorator(binding_setter56,"{Step.DataFetchActivity20.OutTable}");
            bind_dir56 = new BindDirection(_flow.DataFetchActivity20,binding_getter56,binding_setter56,BindTargetType.ToInProperty);
            _flow.DataExporterActivity22.InDirections.Add(bind_dir56);
            this.Activities.Add (_flow.DataExporterActivity22);
            _flow.DataExporterCloseActivity23.Comment = @"";
            _flow.DataExporterCloseActivity23.IconPath = @"";
            this.Activities.Add (_flow.DataExporterCloseActivity23);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.DataDisconnectActivity18.Comment = @"";
            _flow.DataDisconnectActivity18.IconPath = @"";
            VTDPropertyInfoBase pi113 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter57 = new VTDObjectGetter(pi113);
            VTDPropertyInfoBase pi114 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter57 = new VTDObjectSetter(pi114);
            binding_setter57 = new StringFormaterDecorator(binding_setter57,"{Step.DataFetchActivity17.OutTable}");
            bind_dir57 = new BindDirection(_flow.DataFetchActivity17,binding_getter57,binding_setter57,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity18.InDirections.Add(bind_dir57);
            this.Activities.Add (_flow.DataDisconnectActivity18);
            _flow.DataDisconnectActivity21.Comment = @"";
            _flow.DataDisconnectActivity21.IconPath = @"";
            VTDPropertyInfoBase pi115 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter58 = new VTDObjectGetter(pi115);
            VTDPropertyInfoBase pi116 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter58 = new VTDObjectSetter(pi116);
            binding_setter58 = new StringFormaterDecorator(binding_setter58,"{Step.DataFetchActivity20.OutTable}");
            bind_dir58 = new BindDirection(_flow.DataFetchActivity20,binding_getter58,binding_setter58,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity21.InDirections.Add(bind_dir58);
            this.Activities.Add (_flow.DataDisconnectActivity21);
            this.DataCursorActivity24.Comment = @"";
            this.DataCursorActivity24.IconPath = @"";
            VTDPropertyInfoBase pi117 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter59 = new VTDObjectGetter(pi117);
            VTDPropertyInfoBase pi118 = new VTDPropertyInfoBase("InTable");
            VTDBaseSetter binding_setter59 = new VTDObjectSetter(pi118);
            binding_setter59 = new StringFormaterDecorator(binding_setter59,"{Step.DataFetchActivity17.OutTable}");
            bind_dir59 = new BindDirection(_flow.DataFetchActivity17,binding_getter59,binding_setter59,BindTargetType.ToInProperty);
            this.DataCursorActivity24.InDirections.Add(bind_dir59);
            this.DataCursorActivity24_Policy.StartPosition = CursorStartPosition.FirstRecord;
            this.DataCursorActivity24_Policy.StartAtSpecificRow = 1;
            this.DataCursorActivity24_Policy.StartCondition.ColumnName = "";
            this.DataCursorActivity24_Policy.StartCondition.Comparison = ConditionOperator.Equal;
            this.DataCursorActivity24_Policy.StartCondition.Value = "";
            this.DataCursorActivity24_Policy.EndPosition = CursorEndPosition.LastRecord;
            this.DataCursorActivity24_Policy.EndAtSpecificRow = 1;
            this.DataCursorActivity24_Policy.EndCondition.ColumnName = "";
            this.DataCursorActivity24_Policy.EndCondition.Comparison = ConditionOperator.Equal;
            this.DataCursorActivity24_Policy.EndCondition.Value = "";
            this.DataCursorActivity24_Policy.StepType = CursorStepType.Forward;
            this.DataCursorActivity24_Policy.StepSize = 1;
            this.DataCursorActivity24_Policy.ActionAfterLastRecord = CursorActionAfterLastRecord.Wraparound;
            this.DataCursorActivity24.Policy = this.DataCursorActivity24_Policy;
            this.DataCursorActivity24.ReportStepData = true;
            _flow.Loop2.BeforeExecuteStepEvent += this.DataCursorActivity24.ResetCursor;
            _flow.Sequence16.Comment = @"";
            _flow.Sequence16.IconPath = @"";
            _flow.Sequence16.Name = @"Sequence16";
            _flow.Sequence16.Activities.Add (_flow.StServiceCallActivity9);
            _flow.Sequence16.Activities.Add (_flow.StServiceCallActivity11);
            _flow.Sequence16.Activities.Add (_flow.CallQTPTest12);
            _flow.Sequence16.Activities.Add (_flow.StServiceCallActivity14);
            _flow.Sequence16.Activities.Add (_flow.CallQTPTest15);
            XmlDocument StServiceCallActivity9_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity9_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity9_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><GetFlights xmlns=""HP.SOAQ.SampleApp""><DepartureCity>{DataSource.FlidhtInfo!Input.DepartureCity}</DepartureCity><ArrivalCity>{DataSource.FlidhtInfo!Input.ArrivalCity}</ArrivalCity><FlightDate>{DataSource.FlidhtInfo!Input.DepartureDate}</FlightDate></GetFlights></Body></Envelope>");
            _flow.StServiceCallActivity9.InputEnvelope = StServiceCallActivity9_InputEnvelope_Document;
            _flow.StServiceCallActivity9.Comment = @"";
            _flow.StServiceCallActivity9.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity9.Name = @"GetFlights";
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity9.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://localhost:8000/Flights_SOAP" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity9.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.SoapAction = @"HP.SOAQ.SampleApp/IFlightsSoapService/GetFlights";
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity9.Service = @"Flights_Service";
            _flow.StServiceCallActivity9.Port = @"FlightsServiceMethods";
            _flow.StServiceCallActivity9.Operation = @"GetFlights";
            _flow.StServiceCallActivity9.IsOneWay = false;
            _flow.StServiceCallActivity9.SendRequestToService=true;
            _flow.StServiceCallActivity9.FaultExpected=false;
            _flow.StServiceCallActivity9.IsAsync=false;
            _flow.StServiceCallActivity9.TargetNamespace=@"http://tempuri.org/";
            _flow.StServiceCallActivity9.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi119 = new VTDPropertyInfoBase("DepartureDate");
            VTDBaseGetter binding_getter60 = new VTDObjectGetter(pi119);
            VTDPropertyInfoBase pi120 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlights'][1]/*[local-name(.)='FlightDate'][1]");
            VTDBaseSetter binding_setter60 = new VTDXPathSetter(pi120,XmlTypeCode.DateTime);
            bind_dir60 = new BindDirection(this.DataCursorActivity24,binding_getter60,binding_setter60,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir60);
            VTDPropertyInfoBase pi121 = new VTDPropertyInfoBase("DepartureCity");
            VTDBaseGetter binding_getter61 = new VTDObjectGetter(pi121);
            VTDPropertyInfoBase pi122 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlights'][1]/*[local-name(.)='DepartureCity'][1]");
            VTDBaseSetter binding_setter61 = new VTDXPathSetter(pi122,XmlTypeCode.String);
            binding_setter61 = new StringFormaterDecorator(binding_setter61,"{DataSource.FlidhtInfo!Input.DepartureCity}");
            bind_dir61 = new BindDirection(this.DataCursorActivity24,binding_getter61,binding_setter61,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir61);
            VTDPropertyInfoBase pi123 = new VTDPropertyInfoBase("ArrivalCity");
            VTDBaseGetter binding_getter62 = new VTDObjectGetter(pi123);
            VTDPropertyInfoBase pi124 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlights'][1]/*[local-name(.)='ArrivalCity'][1]");
            VTDBaseSetter binding_setter62 = new VTDXPathSetter(pi124,XmlTypeCode.String);
            binding_setter62 = new StringFormaterDecorator(binding_setter62,"{DataSource.FlidhtInfo!Input.ArrivalCity}");
            bind_dir62 = new BindDirection(this.DataCursorActivity24,binding_getter62,binding_setter62,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir62);
            XmlDocument StServiceCallActivity9_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity9_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity9_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity9.ExpectedOutputAttachments = StServiceCallActivity9_ExpectedOutputAttachments_Document;
            XmlDocument StServiceCallActivity9_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity9_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity9_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity9.ExpectedFaultProperties = StServiceCallActivity9_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity9_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity9_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity9_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:p1=""http://www.w3.org/2001/XMLSchema-instance""><Body><GetFlightsResponse xmlns=""HP.SOAQ.SampleApp""><GetFlightsResult><Flight><Airline p1:nil=""true"" /><ArrivalCity p1:nil=""true"" /><ArrivalTime p1:nil=""true"" /><DepartureCity p1:nil=""true"" /><DepartureTime p1:nil=""true"" /><FlightNumber /></Flight></GetFlightsResult></GetFlightsResponse></Body></Envelope>");
            _flow.StServiceCallActivity9.ExpectedOutputProperties = StServiceCallActivity9_ExpectedOutputProperties_Document;
            set_StServiceCallActivity9_checkpoints(_flow.StServiceCallActivity9);
            XmlDocument StServiceCallActivity11_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity11_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity11_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:p1=""http://www.w3.org/2001/XMLSchema-instance""><Body><CreateFlightOrder xmlns=""HP.SOAQ.SampleApp""><FlightOrder><Class>{DataSource.FlidhtInfo!Input.Class}</Class><CustomerName>{DataSource.FlidhtInfo!Input.CustomerName}</CustomerName><DepartureDate>{DataSource.FlidhtInfo!Input.DepartureDate}</DepartureDate><FlightNumber>{Step.OutputProperties.StServiceCallActivity9.Body.GetFlightsResponse.GetFlightsResult.Flight[1].FlightNumber}</FlightNumber><NumberOfTickets>{DataSource.FlidhtInfo!Input.NumberOfTickets}</NumberOfTickets></FlightOrder></CreateFlightOrder></Body></Envelope>");
            _flow.StServiceCallActivity11.InputEnvelope = StServiceCallActivity11_InputEnvelope_Document;
            _flow.StServiceCallActivity11.Comment = @"";
            _flow.StServiceCallActivity11.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity11.Name = @"CreateFlightOrder";
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity11.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://localhost:8000/Flights_SOAP" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity11.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.SoapAction = @"HP.SOAQ.SampleApp/IFlightsSoapService/CreateFlightOrder";
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity11.Service = @"Flights_Service";
            _flow.StServiceCallActivity11.Port = @"FlightsServiceMethods";
            _flow.StServiceCallActivity11.Operation = @"CreateFlightOrder";
            _flow.StServiceCallActivity11.IsOneWay = false;
            _flow.StServiceCallActivity11.SendRequestToService=true;
            _flow.StServiceCallActivity11.FaultExpected=false;
            _flow.StServiceCallActivity11.IsAsync=false;
            _flow.StServiceCallActivity11.TargetNamespace=@"http://tempuri.org/";
            _flow.StServiceCallActivity11.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi125 = new VTDPropertyInfoBase("NumberOfTickets");
            VTDBaseGetter binding_getter63 = new VTDObjectGetter(pi125);
            VTDPropertyInfoBase pi126 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='NumberOfTickets'][1]");
            VTDBaseSetter binding_setter63 = new VTDXPathSetter(pi126,XmlTypeCode.Int);
            bind_dir63 = new BindDirection(this.DataCursorActivity24,binding_getter63,binding_setter63,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir63);
            VTDPropertyInfoBase pi127 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='FlightNumber'][1]");
            VTDBaseGetter binding_getter64 = new VTDXPathGetter(pi127,XmlTypeCode.Int);
            binding_getter64 = new XPathGetterDecorator(binding_getter64,"{Array0}",1);
            VTDPropertyInfoBase pi128 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='FlightNumber'][1]");
            VTDBaseSetter binding_setter64 = new VTDXPathSetter(pi128,XmlTypeCode.Int);
            bind_dir64 = new BindDirection(_flow.StServiceCallActivity9,binding_getter64,binding_setter64,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir64);
            VTDPropertyInfoBase pi129 = new VTDPropertyInfoBase("DepartureDate");
            VTDBaseGetter binding_getter65 = new VTDObjectGetter(pi129);
            VTDPropertyInfoBase pi130 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='DepartureDate'][1]");
            VTDBaseSetter binding_setter65 = new VTDXPathSetter(pi130,XmlTypeCode.DateTime);
            bind_dir65 = new BindDirection(this.DataCursorActivity24,binding_getter65,binding_setter65,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir65);
            VTDPropertyInfoBase pi131 = new VTDPropertyInfoBase("CustomerName");
            VTDBaseGetter binding_getter66 = new VTDObjectGetter(pi131);
            VTDPropertyInfoBase pi132 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='CustomerName'][1]");
            VTDBaseSetter binding_setter66 = new VTDXPathSetter(pi132,XmlTypeCode.String);
            binding_setter66 = new StringFormaterDecorator(binding_setter66,"{DataSource.FlidhtInfo!Input.CustomerName}");
            bind_dir66 = new BindDirection(this.DataCursorActivity24,binding_getter66,binding_setter66,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir66);
            VTDPropertyInfoBase pi133 = new VTDPropertyInfoBase("Class");
            VTDBaseGetter binding_getter67 = new VTDObjectGetter(pi133);
            VTDPropertyInfoBase pi134 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='Class'][1]");
            VTDBaseSetter binding_setter67 = new VTDXPathSetter(pi134,XmlTypeCode.String);
            binding_setter67 = new StringFormaterDecorator(binding_setter67,"{DataSource.FlidhtInfo!Input.Class}");
            bind_dir67 = new BindDirection(this.DataCursorActivity24,binding_getter67,binding_setter67,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir67);
            XmlDocument StServiceCallActivity11_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity11_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity11_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity11.ExpectedOutputAttachments = StServiceCallActivity11_ExpectedOutputAttachments_Document;
            XmlDocument StServiceCallActivity11_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity11_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity11_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity11.ExpectedFaultProperties = StServiceCallActivity11_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity11_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity11_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity11_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><CreateFlightOrderResponse xmlns=""HP.SOAQ.SampleApp""><CreateFlightOrderResult><OrderNumber /></CreateFlightOrderResult></CreateFlightOrderResponse></Body></Envelope>");
            _flow.StServiceCallActivity11.ExpectedOutputProperties = StServiceCallActivity11_ExpectedOutputProperties_Document;
            XmlDocument CallQTPTest12_InputArguments_Document = new XmlDocument();
            CallQTPTest12_InputArguments_Document.PreserveWhitespace = true;
            CallQTPTest12_InputArguments_Document.LoadXml(
@"<Arguments><tOrderNumber>{Step.OutputProperties.StServiceCallActivity11.Body.CreateFlightOrderResponse.CreateFlightOrderResult.OrderNumber}</tOrderNumber><tPassengerName>{Step.InputProperties.StServiceCallActivity11.Body.CreateFlightOrder.FlightOrder.CustomerName}</tPassengerName></Arguments>");
            _flow.CallQTPTest12.InputArguments = CallQTPTest12_InputArguments_Document;
            _flow.CallQTPTest12.Comment = @"";
            _flow.CallQTPTest12.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest12.Name = @"SearchOrderByID.";
            _flow.CallQTPTest12.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.ScriptPath}")) ? @"[QC-TEST];;Subject\demo video_Copy\SearchOrderByID.;;" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.ScriptPath}");
            _flow.CallQTPTest12.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.ActionName}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.ActionName}");
            _flow.CallQTPTest12.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.Description}");
            _flow.CallQTPTest12.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.IsActionSelected}");
            _flow.CallQTPTest12.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.ResultLocation}");
            _flow.CallQTPTest12.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest12.QCScriptPath}");
            VTDPropertyInfoBase pi135 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='CustomerName'][1]");
            VTDBaseGetter binding_getter68 = new VTDXPathGetter(pi135,XmlTypeCode.String);
            VTDPropertyInfoBase pi136 = new VTDPropertyInfoBase("InputArguments","/*[local-name(.)='Arguments'][1]/*[local-name(.)='tPassengerName'][1]");
            VTDBaseSetter binding_setter68 = new VTDXPathSetter(pi136,XmlTypeCode.String);
            binding_setter68 = new StringFormaterDecorator(binding_setter68,"{Step.InputProperties.StServiceCallActivity11.Body.CreateFlightOrder.FlightOrder.CustomerName}");
            bind_dir68 = new BindDirection(_flow.StServiceCallActivity11,binding_getter68,binding_setter68,BindTargetType.ToInProperty);
            _flow.CallQTPTest12.InDirections.Add(bind_dir68);
            VTDPropertyInfoBase pi137 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrderResponse'][1]/*[local-name(.)='CreateFlightOrderResult'][1]/*[local-name(.)='OrderNumber'][1]");
            VTDBaseGetter binding_getter69 = new VTDXPathGetter(pi137,XmlTypeCode.Int);
            VTDPropertyInfoBase pi138 = new VTDPropertyInfoBase("InputArguments","/*[local-name(.)='Arguments'][1]/*[local-name(.)='tOrderNumber'][1]");
            VTDBaseSetter binding_setter69 = new VTDXPathSetter(pi138,XmlTypeCode.String);
            binding_setter69 = new StringFormaterDecorator(binding_setter69,"{Step.OutputProperties.StServiceCallActivity11.Body.CreateFlightOrderResponse.CreateFlightOrderResult.OrderNumber}");
            bind_dir69 = new BindDirection(_flow.StServiceCallActivity11,binding_getter69,binding_setter69,BindTargetType.ToInProperty);
            _flow.CallQTPTest12.InDirections.Add(bind_dir69);
            XmlDocument StServiceCallActivity14_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity14_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity14_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:p1=""http://www.w3.org/2001/XMLSchema-instance""><Body><UpdateFlightOrder xmlns=""HP.SOAQ.SampleApp""><UpdateFlightOrderDetails><CustomerName>Updated Name</CustomerName><OrderNumber>{Step.OutputProperties.StServiceCallActivity11.Body.CreateFlightOrderResponse.CreateFlightOrderResult.OrderNumber}</OrderNumber></UpdateFlightOrderDetails></UpdateFlightOrder></Body></Envelope>");
            _flow.StServiceCallActivity14.InputEnvelope = StServiceCallActivity14_InputEnvelope_Document;
            _flow.StServiceCallActivity14.Comment = @"";
            _flow.StServiceCallActivity14.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity14.Name = @"UpdateFlightOrder";
            _flow.StServiceCallActivity14.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity14.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://localhost:8000/Flights_SOAP" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity14.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity14.TransportProtocol.SOAPProperties.SoapAction = @"HP.SOAQ.SampleApp/IFlightsSoapService/UpdateFlightOrder";
            _flow.StServiceCallActivity14.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity14.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity14.Service = @"Flights_Service";
            _flow.StServiceCallActivity14.Port = @"FlightsServiceMethods";
            _flow.StServiceCallActivity14.Operation = @"UpdateFlightOrder";
            _flow.StServiceCallActivity14.IsOneWay = false;
            _flow.StServiceCallActivity14.SendRequestToService=true;
            _flow.StServiceCallActivity14.FaultExpected=false;
            _flow.StServiceCallActivity14.IsAsync=false;
            _flow.StServiceCallActivity14.TargetNamespace=@"http://tempuri.org/";
            _flow.StServiceCallActivity14.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi139 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrderResponse'][1]/*[local-name(.)='CreateFlightOrderResult'][1]/*[local-name(.)='OrderNumber'][1]");
            VTDBaseGetter binding_getter70 = new VTDXPathGetter(pi139,XmlTypeCode.Int);
            VTDPropertyInfoBase pi140 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='UpdateFlightOrder'][1]/*[local-name(.)='UpdateFlightOrderDetails'][1]/*[local-name(.)='OrderNumber'][1]");
            VTDBaseSetter binding_setter70 = new VTDXPathSetter(pi140,XmlTypeCode.Int);
            bind_dir70 = new BindDirection(_flow.StServiceCallActivity11,binding_getter70,binding_setter70,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity14.InDirections.Add(bind_dir70);
            XmlDocument StServiceCallActivity14_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity14_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity14_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity14.ExpectedOutputAttachments = StServiceCallActivity14_ExpectedOutputAttachments_Document;
            XmlDocument StServiceCallActivity14_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity14_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity14_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity14.ExpectedFaultProperties = StServiceCallActivity14_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity14_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity14_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity14_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><UpdateFlightOrderResponse xmlns=""HP.SOAQ.SampleApp"" /></Body></Envelope>");
            _flow.StServiceCallActivity14.ExpectedOutputProperties = StServiceCallActivity14_ExpectedOutputProperties_Document;
            set_StServiceCallActivity14_checkpoints(_flow.StServiceCallActivity14);
            XmlDocument CallQTPTest15_InputArguments_Document = new XmlDocument();
            CallQTPTest15_InputArguments_Document.PreserveWhitespace = true;
            CallQTPTest15_InputArguments_Document.LoadXml(
@"<Arguments><tOrderNumber>{Step.InputProperties.StServiceCallActivity14.Body.UpdateFlightOrder.UpdateFlightOrderDetails.OrderNumber}</tOrderNumber><tPassengerName>{Step.InputProperties.StServiceCallActivity14.Body.UpdateFlightOrder.UpdateFlightOrderDetails.CustomerName}</tPassengerName></Arguments>");
            _flow.CallQTPTest15.InputArguments = CallQTPTest15_InputArguments_Document;
            _flow.CallQTPTest15.Comment = @"";
            _flow.CallQTPTest15.IconPath = @"AddIns\ServiceTest\UFT\toolbox_qtp.png";
            _flow.CallQTPTest15.Name = @"SearchOrderByID.";
            _flow.CallQTPTest15.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.ScriptPath}")) ? @"[QC-TEST];;Subject\demo video_Copy\SearchOrderByID.;;" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.ScriptPath}");
            _flow.CallQTPTest15.ActionName = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.ActionName}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.ActionName}");
            _flow.CallQTPTest15.Description = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.Description}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.Description}");
            _flow.CallQTPTest15.IsActionSelected = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.IsActionSelected}")) ? @"True" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.IsActionSelected}");
            _flow.CallQTPTest15.ResultLocation = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.ResultLocation}")) ? @"RunQTPReport\" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.ResultLocation}");
            _flow.CallQTPTest15.QCScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.QCScriptPath}")) ? @"" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallQTPTest15.QCScriptPath}");
            VTDPropertyInfoBase pi141 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='UpdateFlightOrder'][1]/*[local-name(.)='UpdateFlightOrderDetails'][1]/*[local-name(.)='CustomerName'][1]");
            VTDBaseGetter binding_getter71 = new VTDXPathGetter(pi141,XmlTypeCode.String);
            VTDPropertyInfoBase pi142 = new VTDPropertyInfoBase("InputArguments","/*[local-name(.)='Arguments'][1]/*[local-name(.)='tPassengerName'][1]");
            VTDBaseSetter binding_setter71 = new VTDXPathSetter(pi142,XmlTypeCode.String);
            binding_setter71 = new StringFormaterDecorator(binding_setter71,"{Step.InputProperties.StServiceCallActivity14.Body.UpdateFlightOrder.UpdateFlightOrderDetails.CustomerName}");
            bind_dir71 = new BindDirection(_flow.StServiceCallActivity14,binding_getter71,binding_setter71,BindTargetType.ToInProperty);
            _flow.CallQTPTest15.InDirections.Add(bind_dir71);
            VTDPropertyInfoBase pi143 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='UpdateFlightOrder'][1]/*[local-name(.)='UpdateFlightOrderDetails'][1]/*[local-name(.)='OrderNumber'][1]");
            VTDBaseGetter binding_getter72 = new VTDXPathGetter(pi143,XmlTypeCode.Int);
            VTDPropertyInfoBase pi144 = new VTDPropertyInfoBase("InputArguments","/*[local-name(.)='Arguments'][1]/*[local-name(.)='tOrderNumber'][1]");
            VTDBaseSetter binding_setter72 = new VTDXPathSetter(pi144,XmlTypeCode.String);
            binding_setter72 = new StringFormaterDecorator(binding_setter72,"{Step.InputProperties.StServiceCallActivity14.Body.UpdateFlightOrder.UpdateFlightOrderDetails.OrderNumber}");
            bind_dir72 = new BindDirection(_flow.StServiceCallActivity14,binding_getter72,binding_setter72,BindTargetType.ToInProperty);
            _flow.CallQTPTest15.InDirections.Add(bind_dir72);
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    